<?xml version="1.0" encoding="utf-8"?>
<Database Name="HRDB" Class="hrDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WHIOGLFOCE9ME2U;Initial Catalog=HRDB;Integrated Security=True" SettingsObjectName="ORM.Properties.Settings" SettingsPropertyName="HRDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.accinformation" Member="accinformation">
    <Type Name="accinformation">
      <Column Name="acc_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="acc_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="acc_describe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="acc_formula" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="acc_undeductions" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="acc_deductionsway" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="acc_maker" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="acc_madetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="acc_changetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="accinformation_cstructure" Member="cstructure" OtherKey="acc_id" Type="cstructure" />
    </Type>
  </Table>
  <Table Name="dbo.sresult" Member="sresult">
    <Type Name="sresult">
      <Column Name="sal_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sre_sodeliver" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sre_sodeduct" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sre_actdeliver" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="salary_sresult" Member="salary" ThisKey="sal_id" Type="salary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.countrydeductions" Member="countrydeductions">
    <Type Name="countrydeductions">
      <Column Name="cou_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cou_basis" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cou_up" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cou_down" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cou_percent" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cstructure" Member="cstructure">
    <Type Name="cstructure">
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="acc_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fac_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cst_value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="accinformation_cstructure" Member="accinformation" ThisKey="acc_id" Type="accinformation" IsForeignKey="true" />
      <Association Name="factor_cstructure" Member="factor" ThisKey="fac_id" Type="factor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.deductionsdomain" Member="deductionsdomain">
    <Type Name="deductionsdomain">
      <Column Name="ded_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ded_up" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ded_down" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ded_fixedvalue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ded_percent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ded_type" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.factor" Member="factor">
    <Type Name="factor">
      <Column Name="fac_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fty_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fac_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fac_isdefault" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="fac_describe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fac_maker" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="fac_madetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fac_changetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="boo_flag" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="factor_cstructure" Member="cstructure" OtherKey="fac_id" Type="cstructure" />
      <Association Name="ftype_factor" Member="ftype" ThisKey="fty_id" Type="ftype" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ftype" Member="ftype">
    <Type Name="ftype">
      <Column Name="fty_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fty_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fty_describe" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fty_maker" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="fty_madetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fty_changetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ftype_factor" Member="factor" OtherKey="fty_id" Type="factor" />
    </Type>
  </Table>
  <Table Name="dbo.person" Member="person">
    <Type Name="person">
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="per_sno" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="per_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="per_sex" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="per_department" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="per_jiontime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="person_remresult" Member="remresult" OtherKey="per_id" Type="remresult" />
    </Type>
  </Table>
  <Table Name="dbo.remresult" Member="remresult">
    <Type Name="remresult">
      <Column Name="per_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sal_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="acc_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="acc_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fac_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fac_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fty_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fac_value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="person_remresult" Member="person" ThisKey="per_id" Type="person" IsForeignKey="true" />
      <Association Name="salary_remresult" Member="salary" ThisKey="sal_id" Type="salary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.salary" Member="salary">
    <Type Name="salary">
      <Column Name="sal_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sal_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="sal_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sal_month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sal_madetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sal_isexamine" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="sal_examiner" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="sal_examinetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sal_isgrant" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="sal_granttime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="salary_sresult" Member="sresult" OtherKey="sal_id" Type="sresult" />
      <Association Name="salary_remresult" Member="remresult" AccessModifier="Internal" OtherKey="sal_id" Type="remresult" />
    </Type>
  </Table>
  <Table Name="dbo.sreport" Member="sreport">
    <Type Name="sreport">
      <Column Name="sre_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sre_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sre_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sre_month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sre_madetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sre_title" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="sre_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="sre_type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="sre_iscustom" Type="System.Char" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>